In [85]:
import pandas as pd
import numpy as np
import random
import json

In [64]:
matches = []
teams = np.arange(1,21)

while len(teams) != 0:
    one = random.randint(1,20)
    two = random.randint(1,20)
    if one in teams and two in teams and one != two:
        matches.append([one,two])
        teams = np.setdiff1d(teams,matches[len(matches)-1])
        print(teams)

print(matches)

[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 19 20]
[ 1  2  3  5  6  7  8  9 11 12 13 14 15 16 19 20]
[ 1  2  3  5  6  7  8  9 11 12 13 14 16 19]
[ 1  3  5  6  7  8  9 11 12 13 14 16]
[ 1  3  6  7  8 11 12 13 14 16]
[ 1  3  6 11 12 13 14 16]
[ 1  6 11 12 13 14]
[ 1  6 12 14]
[ 1 14]
[]
[[4, 18], [17, 10], [20, 15], [2, 19], [5, 9], [7, 8], [16, 3], [11, 13], [6, 12], [14, 1]]


In [65]:
len(matches)

10

In [109]:
def get_data(matchday, min):
    df = pd.DataFrame()
    size = 10
    df['matchday'] = np.full((size,), matchday) #np.random.randint(0,100, size)
    df['minute'] = np.full((size,), min)
    df['date'] = np.full((size,), "2022-03-27")
    df['timestamp'] = np.full((size,), "2022-03-27 10:05:00")
    
    df['teamId_1'] = [x[0] for x in matches]
    df['teamId_2'] = [x[1] for x in matches]
    
    df['goal_1'] = np.full((size,), 0)
    df['goal_2'] = np.full((size,), 0)
    
    df['poss_1'] = np.random.randint(30, 70, size)
    df['poss_2'] = 100-df['poss_1']
    
    df['passes_attp_1'] = np.random.randint(5, 40, size)
    df['pass_comp_1'] = [x/10 for x in random.sample(range(400, 1000), size)]
    
    df['shots_attp_1'] = np.random.choice([0,0,0,0,1,1,2,3,4], size)
    df['shots_trg_1'] = df['shots_attp_1']*(df['pass_comp_1']/100).astype('int')
    
    df['passes_attp_2'] = np.random.randint(5, 40, size)
    df['pass_comp_2'] = [x/10 for x in random.sample(range(0, 1000), size)]
    
    df['shots_attp_2'] = np.random.choice([0,0,0,0,1,1,2,3,4], size)
    df['shots_trg_2'] = df['shots_attp_2']*(df['pass_comp_2']/100).astype('int')

    return df

In [6]:
np.full((10,), 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [110]:
df = get_data(1,1)
df.head(10)

matchday  minute        date            timestamp  teamId_1  teamId_2  \
0         1       1  2022-03-27  2022-03-27 10:05:00         4        18   
1         1       1  2022-03-27  2022-03-27 10:05:00        17        10   
2         1       1  2022-03-27  2022-03-27 10:05:00        20        15   
3         1       1  2022-03-27  2022-03-27 10:05:00         2        19   
4         1       1  2022-03-27  2022-03-27 10:05:00         5         9   
5         1       1  2022-03-27  2022-03-27 10:05:00         7         8   
6         1       1  2022-03-27  2022-03-27 10:05:00        16         3   
7         1       1  2022-03-27  2022-03-27 10:05:00        11        13   
8         1       1  2022-03-27  2022-03-27 10:05:00         6        12   
9         1       1  2022-03-27  2022-03-27 10:05:00        14         1   

   goal_1  goal_2  poss_1  poss_2  passes_attp_1  pass_comp_1  shots_attp_1  \
0       0       0      69      31             23         93.6             1   
1       0       0      42      58              8         59.9             0   
2       0       0      54      46             13         84.5             1   
3       0       0      69      31              6         80.9             4   
4       0       0      45      55              7         92.9             0   
5       0       0      48      52             12         80.6             0   
6       0       0      45      55             25         40.9             1   
7       0       0      58      42             19         71.0             4   
8       0       0      58      42             26         88.5             0   
9       0       0      30      70             36         99.3             3   

   shots_trg_1  passes_attp_2  pass_comp_2  shots_attp_2  shots_trg_2  
0            0             18         67.1             3            0  
1            0              9         27.7             2            0  
2            0             31         26.2             0            0  
3            0              8         35.3             2            0  
4            0             16          0.2             2            0  
5            0             13         86.5             0            0  
6            0             34         89.5             1            0  
7            0             18         22.0             1            0  
8            0             14         97.3             3            0  
9            0             17          2.9             0            0

In [111]:
result = df.to_json('data/min1.json', orient="records")

In [105]:
nextdf = get_data(1,1)
nextdf['goal_1'] = nextdf['goal_1']+np.random.choice([0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,2],10)
nextdf['goal_2'] = nextdf['goal_2']+np.random.choice([0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,2],10)
nextdf.head(10)

matchday  minute  teamId_1  teamId_2  goal_1  goal_2  poss_1  poss_2  \
0         1       1         4        18       0       1      64      36   
1         1       1        17        10       0       0      43      57   
2         1       1        20        15       1       0      56      44   
3         1       1         2        19       1       2      38      62   
4         1       1         5         9       2       0      37      63   
5         1       1         7         8       0       0      50      50   
6         1       1        16         3       0       0      51      49   
7         1       1        11        13       1       2      53      47   
8         1       1         6        12       0       1      40      60   
9         1       1        14         1       0       0      51      49   

   passes_attp_1  pass_comp_1  shots_attp_1  shots_trg_1  passes_attp_2  \
0              9         69.9             1            0             12   
1             11         49.9             1            0             11   
2             35         85.8             0            0             13   
3             25         93.2             0            0             24   
4             37         81.9             1            0             31   
5             12         53.5             0            0             21   
6             20         69.3             0            0             10   
7             17         62.6             0            0             32   
8             15         95.2             0            0             26   
9             27         45.7             4            0             31   

   pass_comp_2  shots_attp_2  shots_trg_2  
0         25.6             3            0  
1         69.2             0            0  
2         45.4             1            0  
3         85.0             2            0  
4         43.0             0            0  
5          5.1             0            0  
6         55.4             0            0  
7         75.9             3            0  
8         11.7             4            0  
9         36.4             3            0

In [112]:
prevDF = df
for i in range(2,15):
    nextDF = get_data(1,i)
    nextDF['goal_1'] = prevDF['goal_1']+np.random.choice([0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,2],10)
    nextDF['goal_2'] = prevDF['goal_2']+np.random.choice([0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,2],10)
    result = nextDF.to_json(f'data/min{i}.json', orient="records")
    prevDF = nextDF

In [106]:
from pyspark.sql.functions import col, lit
from pyspark.sql.types import StructType,StructField, StringType, IntegerType, DoubleType, BooleanType

In [113]:
df=spark.read.option("multiline","true").json("./data/min1.json")
df.show(10,False)

+----------+------+------+--------+------+-----------+-----------+-------------+-------------+------+------+------------+------------+-----------+-----------+--------+--------+-------------------+
|date      |goal_1|goal_2|matchday|minute|pass_comp_1|pass_comp_2|passes_attp_1|passes_attp_2|poss_1|poss_2|shots_attp_1|shots_attp_2|shots_trg_1|shots_trg_2|teamId_1|teamId_2|timestamp          |
+----------+------+------+--------+------+-----------+-----------+-------------+-------------+------+------+------------+------------+-----------+-----------+--------+--------+-------------------+
|2022-03-27|0     |0     |1       |1     |93.6       |67.1       |23           |18           |69    |31    |1           |3           |0          |0          |4       |18      |2022-03-27 10:05:00|
|2022-03-27|0     |0     |1       |1     |59.9       |27.7       |8            |9            |42    |58    |0           |2           |0          |0          |17      |10      |2022-03-27 10:05:00|
|2022-03-27|0  

In [114]:
df.printSchema()

root
 |-- date: string (nullable = true)
 |-- goal_1: long (nullable = true)
 |-- goal_2: long (nullable = true)
 |-- matchday: long (nullable = true)
 |-- minute: long (nullable = true)
 |-- pass_comp_1: double (nullable = true)
 |-- pass_comp_2: double (nullable = true)
 |-- passes_attp_1: long (nullable = true)
 |-- passes_attp_2: long (nullable = true)
 |-- poss_1: long (nullable = true)
 |-- poss_2: long (nullable = true)
 |-- shots_attp_1: long (nullable = true)
 |-- shots_attp_2: long (nullable = true)
 |-- shots_trg_1: long (nullable = true)
 |-- shots_trg_2: long (nullable = true)
 |-- teamId_1: long (nullable = true)
 |-- teamId_2: long (nullable = true)
 |-- timestamp: string (nullable = true)

